Add configure script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -27,21 +27,10 @@
 # SOFTWARE.
 #
 error() {
-  rm test.c
   printf "$@\n"
   exit 1
 }
 init() {
-  printf "checking for prefix... "
-  if [ ! $PREFIX ]; then
-    echo "/"
-  else
-    if [ -e $PREFIX/bin ]; then
-      echo "$PREFIX"
-    else
-      error "\n$PREFIX/bin/ not found, prefix cannot be used"
-    fi
-  fi
   printf "checking for install... "
   if ! command -v install; then
     error "not found"
@@ -64,50 +53,35 @@ init() {
   fi
   printf "$CC\n"
   printf "checking whether the compiler supports GNU C99... "
-  echo "int main(){}" > test.c
-  sleep 0.1
-  ($CC -x c -o /dev/null -std=gnu99 test.c) >/dev/null 2>&1 && printf "ok\n" || error "no"
-  rm test.c
+  (echo "int main(){}" | $CC -x c -o /dev/null -std=gnu99 -) >/dev/null 2>&1 && printf "ok\n" || error "no"
   if [ $STATIC_COMPILE ]; then
     printf "checking whether the compiler supports -static compile... "
-    echo "int main(){}" > test.c
-    sleep 0.1
-    $CC -static -x c -o /dev/null -std=gnu99 test.c >/dev/null 2>&1 && printf "ok\n" || error "no"
-    rm test.c
+    echo "int main(){}" | $CC -static -x c -o /dev/null -std=gnu99 - >/dev/null 2>&1 && printf "ok\n" || error "no"
   fi
 }
 test_and_add_cflag() {
   printf "checking whether the compiler supports $1... "
-  echo "int main(){}" > test.c
-  sleep 0.1
-  if $CC $1 -x c -o /dev/null test.c >/dev/null 2>&1
-  then
-    printf "ok\n" && export CFLAG="$CFLAG $1"
+  if echo "int main(){}" | $CC $1 -x c -o /dev/null - >/dev/null 2>&1; then
+    printf "ok\n" && export CFLAGS="$CFLAGS $1"
   else
     printf "no\n"
   fi
-  rm test.c
 }
 test_and_add_ldflag() {
   printf "checking for $1... "
-  echo "int main(){}" > test.c
-  sleep 0.1
   if [ $STATIC_COMPILE ]; then
-    if $CC -static -x c -o /dev/null test.c $1 >/dev/null 2>&1
-    then
-      printf "ok\n" && export LDFLAG="$LDFLAG $1"
+    if echo "int main(){}" | $CC -static -x c -o /dev/null - $1 >/dev/null 2>&1; then
+      printf "ok\n" && export LD_FLAGS="$LD_FLAGS $1"
     else
       printf "no\n"
     fi
   else
-    if $CC -x c -o /dev/null test.c $1 >/dev/null 2>&1
-    then
-      printf "ok\n" && export LDFLAG="$LDFLAG $1"
+    if echo "int main(){}" | $CC -x c -o /dev/null - $1 >/dev/null 2>&1; then
+      printf "ok\n" && export LD_FLAGS="$LD_FLAGS $1"
     else
       printf "no\n"
     fi
   fi
-  rm test.c
 }
 check_header() {
   printf "checking for header $i... "
@@ -121,33 +95,21 @@ check_lib() {
   printf "found\n"
 }
 default_cflag() {
-  # Auto var init.
-  test_and_add_cflag "-ftrivial-auto-var-init=zero"
-  # Link-Time Optimization.
+  test_and_add_cflag "-ftrivial-auto-var-init=pattern"
+  test_and_add_cflag "-fcf-protection=full"
   test_and_add_cflag "-flto"
-  # Position-Independent Executables.
   test_and_add_cflag "-fPIE"
-  # No-eXecute.
-  test_and_add_cflag "-Wl,-znoexecstack"
-  # Relocation Read-Only.
-  test_and_add_cflag "-Wl,-znow"
-  # Stack Canary.
+  test_and_add_cflag "-pie"
+  test_and_add_cflag "-Wl,-z,relro"
+  test_and_add_cflag "-Wl,-z,noexecstack"
+  test_and_add_cflag "-Wl,-z,now"
   test_and_add_cflag "-fstack-protector-all"
-  # Stack Clash Protection.
   test_and_add_cflag "-fstack-clash-protection"
-  # Shadow Stack.
   test_and_add_cflag "-mshstk"
-  # Fortified Source.
   test_and_add_cflag "-D_FORTIFY_SOURCE=3"
-  # Disable warnings.
   test_and_add_cflag "-Wno-unused-result"
-  # Other "one-key" optimization.
   test_and_add_cflag "-O2"
-  # Warning as error.
-  test_and_add_cflag "-Werror"
-  # Build id.
   test_and_add_cflag "-Wl,--build-id=sha1"
-  # Fix bionic on Android.
   test_and_add_cflag "-ffunction-sections"
   test_and_add_cflag "-fdata-sections"
   test_and_add_cflag "-Wl,--gc-sections"
@@ -159,28 +121,20 @@ default_cflag() {
   test_and_add_ldflag "-lpthread"
 }
 dev_cflag() {
-  # GNU Symbolic Debugger.
   test_and_add_cflag "-ggdb"
-  # Disable other optimizations.
   test_and_add_cflag "-O0"
   test_and_add_cflag "-fno-omit-frame-pointer"
-  # Disable Relocation Read-Only.
-  test_and_add_cflag "-Wl,-znorelro"
-  # Disable No-eXecute.
-  test_and_add_cflag "-Wl,-zexecstack"
-  # Disable Stack Canary.
+  test_and_add_cflag "-Wl,-z,norelro"
+  test_and_add_cflag "-Wl,-z,execstack"
   test_and_add_cflag "-fno-stack-protector"
-  # Warning Options.
   test_and_add_cflag "-Wall"
   test_and_add_cflag "-Wextra"
   test_and_add_cflag "-pedantic"
   test_and_add_cflag "-Wconversion"
   test_and_add_cflag "-Wno-newline-eof"
-  # ASAN.
+  test_and_add_cflag "-Wno-gnu-zero-variadic-macro-arguments"
   test_and_add_cflag "-fsanitize=address"
-  # Build id.
   test_and_add_cflag "-Wl,--build-id=sha1"
-  # Fix bionic on Android.
   test_and_add_cflag "-ffunction-sections"
   test_and_add_cflag "-fdata-sections"
   test_and_add_cflag "-Wl,--gc-sections"
@@ -202,7 +156,7 @@ check_headers_and_libs() {
   done
   # Check library.
   if [ $STATIC_COMPILE ]; then
-    for i in libc.a libcap.a libseccomp.so; do
+    for i in libc.a libcap.a libseccomp.a; do
       check_lib $i
     done
   else
@@ -211,10 +165,28 @@ check_headers_and_libs() {
     done
   fi
 }
+show_help() {
+  echo "Usage: ./configure [OPTION]..."
+  echo "    -h, --help          show help"
+  echo "    -s, --static        compile static binary"
+  echo "    -d, --dev           compile dev version"
+}
+while [ $1 ]; do
+  case $1 in
+  "-h" | "--help") show_help && exit ;;
+  "-s" | "--static") export STATIC_COMPILE=true ;;
+  "-d" | "--dev") export DEV_BUILD=true ;;
+  esac
+  shift
+done
 init
 check_headers_and_libs
-default_cflag
-echo $CFLAG
-export CFLAG=
-dev_cflag
-echo $CFLAG
+if [ ! $DEV_BUILD ]; then
+  default_cflag
+else
+  dev_cflag
+fi
+printf "create config.mk... "
+echo "CFLAGS = $CFLAGS" >config.mk
+echo "LD_FLAGS = $LD_FLAGS" >>config.mk
+printf "ok\n"
